apiVersion: batch/v1
kind: Job
metadata:
  name: secret-syncer
spec:
  template:
    spec:
      containers:
        - name: secret-sync-container
          image: <fill in>
          env:
            - name: env
              value: prod
            - name: PROJECT_ID
              value: <project_id>
      restartPolicy: Never
